### ISSUE TITLE
bluebird (promise framework) generates warning

### ISSUE THREAD

**Issue by henebb** [aurelia/templating-router#31]
Hi!

We've started using bluebird. By simply adding `import 'bluebird'`.
But bluebird generates a console warning that is a bit "annoying". I think it's in the aurelia code: https://github.com/aurelia/templating-router/blob/master/src/route-href.js#L45 The promise doesn't return anything. It should at least return null, see: https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it

The warning is this:
`Warning: a promise was created in a handler but was not returned from it
    at RouteHref.processChange (http://localhost:9000/jspm_packages/npm/aurelia-templating-router@1.0.0-rc.1.0.0/route-href.js:63:45)
    at RouteHref.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating-router@1.0.0-rc.1.0.0/route-href.js:45:12)
    at Controller.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:3370:24)
    at View.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:1433:24)
    at Controller.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:3362:19)
    at Controller.automate (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:3307:12)
    at RouterView.swap (http://localhost:9000/jspm_packages/npm/aurelia-templating-router@1.0.0-rc.1.0.0/router-view.js:209:38)
    at http://localhost:9000/jspm_packages/npm/aurelia-templating-router@1.0.0-rc.1.0.0/router-view.js:169:15`

**Comment by EisenbergEffect** [comment]
I've pushed the fix suggested here. However, this isn't likely to fix it fully because there are a number of ways that Aurelia uses promises correctly that simply confuse bluebird. You may want to consider configuring bluebird to ignore those warnings. You can do it like this:

```
Promise.config({
  warnings: {
    wForgottenReturn: false
  }
});
```

**Comment by henebb** [comment]
Great! Thanks a lot!
